add some changes

diff --git a/services-on-interface/services-on-interface b/services-on-interface/services-on-interface
--- a/services-on-interface/services-on-interface
+++ b/services-on-interface/services-on-interface
@@ -1,23 +1,29 @@
 #!/bin/bash -
 
+### debugging
+# ifup -v eth0:www
+# ifdown -v eth0:www
+# set -x
+
 IF_ALIAS_NAME=eth0:www
 IF_ALIAS_ADDR="11.11.11.11/23"
 IF_ALIAS_LABEL=${IF_ALIAS_NAME/*:/}
-# insert service name with space between : "service1 service2"
 SERVICES="apache2"
 SCRIPT_NAME=$0
 
 [ $IFACE != $IF_ALIAS_NAME ] && exit 0
 
 set_addr() {
-    ip -o -4 -h add show label $IFACE | grep -v $IF_ALIAS_ADDR && ip addr add $IF_ALIAS_ADDR dev $IFACE label $IFACE || logger "$SCRIPT_NAME : unable to set address $IF_ALIAS_ADDR on $IFACE" 
+    showif=$(ip -o -4 -h addr show label $IFACE &> /dev/null)
+    test -z $showif && ip addr add $IF_ALIAS_ADDR dev $IFACE label $IFACE || logger "$SCRIPT_NAME : unable to set address $IF_ALIAS_ADDR on $IFACE"
 }
 unset_addr() {
-    ip -o -4 -h add show label $IFACE | grep $IF_ALIAS_ADDR && ip addr del $IF_ALIAS_ADDR dev $IFACE label $IFACE || logger "$SCRIPT_NAME : unable to unset address $IF_ALIAS_ADDR from $IFACE" 
+    showif=$(ip -o -4 -h addr show label $IFACE /dev/null)
+    ! test -z $showif && ip addr del $IF_ALIAS_ADDR dev $IFACE label $IFACE || logger "$SCRIPT_NAME : unable to unset address $IF_ALIAS_ADDR on $IFACE"
 }
 
 start_service() {
-    if ! ping -qc 1 ${IF_ALIAS_ADDR/\/*/} ; then
+    if ! ping -qc 1 ${IF_ALIAS_ADDR/\/*/} &> /dev/null ; then
         if set_addr ; then
             logger "$SCRIPT_NAME : setting ip address on $IFACE"
             for svc in $SERVICES ; do
